name: Terraform CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main", "destroy"]

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Init
        run: terraform -chdir=terraform init

      - name: Validate
        run: |
          terraform -chdir=terraform fmt -check
          terraform -chdir=terraform validate

      - name: Plan
        if: github.event_name == 'pull_request'
        run: terraform -chdir=terraform plan -input=false

      - name: Destroy
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform -chdir=terraform destroy -auto-approve -input=false

      #- name: Apply
      #  if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      #  run: terraform -chdir=terraform apply -auto-approve -input=false

      - name: Show outputs
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform -chdir=terraform output